#ifndef BEESSTATS_H
#define BEESSTATS_H

#include <cmath>
#include <vector>
#include <iostream>

/**
 * @brief Bees Statistics Class
 *
 * This class holds the statistics generated by a run of the Bees algorithm.
 *
 */
class BeesStats
{
private:
    int                               m_totalParameters;
    int                               m_numRuns;
    double                            m_sumFitness;
    double                            m_meanFitness;
    std::vector<double>               m_sumData;
    std::vector<double>               m_fitnessData;
    std::vector<double>               m_meanData;
    std::vector<double>               m_stdDev;
    std::vector<std::vector<double> > m_data;

public:
    BeesStats(const int &totParameters, const int& numRuns);
   ~BeesStats() {}

    void addData(const double& bestFitness,
                 const std::vector<double>& parameters);
    void getMean(double& fitness,
                 std::vector<double>& parameters);
    void getStdDev(double& fitnessStdDev,
                   double& totStdDev,
                   std::vector<double>& stdDevParameters);

};

#endif
