#include "nmfDatabase.h"
#include "nmfLogger.h"
#include "nmfUtils.h"
//#include "nmfStructsQt.h"

#include <string>
#include <set>
#include <map>
#include <memory>
#include <vector>
#include <functional>
#include <algorithm>
#include <numeric>
#include <iterator>
#include <cmath>
#include <cassert>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdlib>

#include <QAction>
#include <QApplication>
#include <QButtonGroup>
//#include <QCategoryAxis>
#include <QCheckBox>
#include <QColor>
#include <QComboBox>
#include <QDir>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFileDialog>
#include <QFrame>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QInputDialog>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMainWindow>
#include <QMap>
#include <QMenu>
#include <QMessageBox>
#include <QMouseEvent>
#include <QPointer>
#include <QPushButton>
#include <QProgressDialog>
#include <QRadioButton>
#include <QSettings>
#include <QSpacerItem>
#include <QSpinBox>
#include <QSplitter>
#include <QStandardItemModel>
#include <QStringList>
#include <QTabWidget>
#include <QTableWidget>
#include <QTextEdit>
#include <QToolTip>
#include <QUiLoader>
#include <QValidator>
//#include <QValueAxis>
#include <QVariant>
#include <QVBoxLayout>
#include <QVector>

#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/io.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/range/algorithm_ext/erase.hpp>

